project:
  type: book
  output-dir: docs

book:
  title: Containers for Scientists
  author: Candace Savonen
  date: "10/11/2024"
  favicon: assets/favicon.ico
  bread-crumbs: false

  page-navigation: true
  search: true
  repo-url: https://github.com/fhdsl/Containers_for_Scientists
  repo-actions: [edit]
  issue-url: https://docs.google.com/forms/d/e/1FAIpQLSfBvVELBg8lcynKj0TrzMlov1zil-Sbkh9VhMKRcSpeo1xo6g/viewform

  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-why-containers.qmd
    - 03-using-containers.qmd
    - 04-modifying-containers.qmd
    - 05-more-about-dockerfiles.qmd
    - 06-sharing-containers.qmd
    - 07-cleaning-up.qmd
    - 08-troubleshooting.qmd
    - 09-advanced-techniques.qmd
    - References.qmd

  sidebar:
    logo: "img/logo.png"
    logo-href: "https://hutchdatascience.org/"
    foreground: "#1B365D"

  page-footer:
    left: |
      This book was built with <a href="https://quarto.org/" style="color: #fff;">Quarto</a> using
      <a href="https://github.com/fhdsl/OTTR_Quarto" style="color: #fff;">OTTR</a>.
    center: |
      All illustrations <a href="https://creativecommons.org/licenses/by/4.0/" style="color: #fff;">CC-BY. </a>
      <br>
      All other materials <a href= "https://creativecommons.org/licenses/by/4.0/" style="color: #fff;"> CC-BY </a> unless noted otherwise.
    right:
      - icon: github
        href: https://github.com/
      - icon: slack
        href: https://fhdata.slack.com/join/signup#/domain-signup



bibliography: references.bib

format:
  html:
    grid:
       sidebar-width: 260px
    css: style.css
    linkcolor: "#00C1D5"
    mainfont: "Karla"

    sidebar: true
    toc: true

    code-link: true
    code-copy: true

    link-external-newwindow: true

    image: img/favicon.ico
    license: "CC BY"
knitr:
  opts_chunk:
    fig.path: "resources/images/figure/"
