project:
  type: book
  output-dir: docs

book:
  title: Containers for Scientists
  author: Candace Savonen
  date: "10/11/2024"
  favicon: assets/ITN_favicon.ico
  bread-crumbs: false

  page-navigation: true
  search: true
  repo-url: https://github.com/fhdsl/Containers_for_Scientists
  repo-actions: [edit]
  issue-url: https://forms.gle/hc8Xt3Y2Znjb6M4Y7
  google-analytics: "G-L8RNG6K22F"

  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-why-containers.qmd
    - 03-using-containers.qmd
    - 04-using-volumes.qmd
    - 05-modifying-containers.qmd
    - 06-writing-dockerfiles.qmd
    - 07-sharing-images.qmd
    - 08-cleaning-up.qmd
    - 09-troubleshooting.qmd
    - 10-IDE-from-containers.qmd
    - 11-advanced-techniques.qmd
    - References.qmd
    - About.qmd

  sidebar:
    logo: "assets/ITN_logo.png"
    logo-href: "https://www.itcrtraining.org/"
    foreground: "#1B365D"

  page-footer:
    left: |
      This book was built with <a href="https://quarto.org/" style="color: #0000FF;">Quarto</a> using
      <a href="https://github.com/fhdsl/OTTR_Quarto" style="color: #fff;">OTTR</a>.
    center: |
      All illustrations <a href="https://creativecommons.org/licenses/by/4.0/" style="color: #0000FF;">CC-BY. </a>
      <br>
      All other materials <a href= "https://creativecommons.org/licenses/by/4.0/" style="color: #0000FF;"> CC-BY </a> unless noted otherwise.
    right:
      - icon: github
        href: https://github.com/
      - icon: slack
        href: https://fhdata.slack.com/join/signup#/domain-signup



bibliography: references.bib

format:
  html:
    grid:
       sidebar-width: 260px
    css: assets/style_ITN.css
    linkcolor: "#e0471c"
    mainfont: "Karla"

    sidebar: true
    toc: true

    code-link: true
    code-copy: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"

    link-external-newwindow: true

    image: assets/ITN_favicon.ico
    license: "CC BY"
knitr:
  opts_chunk:
    fig.path: "resources/images/figure/"
